language: emacs-lisp
sudo: false

env:
  - EVM_EMACS=emacs-26.1-travis-linux-xenial
  - EVM_EMACS=emacs-26.2-travis-linux-xenial
  - EVM_EMACS=emacs-26.3-travis-linux-xenial
  - EVM_EMACS=emacs-git-snapshot-travis-linux-xenial

matrix:
  fast_finish: true
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis-linux-xenial

before_install:
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.org)|(.png)|(.pdf)|(.html)|^(LICENSE)|^(docs)'; then
      echo "Only doc files were updated, not running the CI."
      exit
    fi

install:
  - echo "Importing elpa key..."
  - EMACS_GNUPGHOME=$HOME/.emacs.d/elpa/gnupg
  - mkdir -p "$EMACS_GNUPGHOME"
  - chmod 700 "$EMACS_GNUPGHOME"
  - wget 'https://git.savannah.gnu.org/cgit/emacs.git/plain/etc/package-keyring.gpg'
  - gpg --homedir "$EMACS_GNUPGHOME" --import package-keyring.gpg

  - export PATH="$HOME/.evm/bin:$PATH"
  - export PATH="$HOME/.cask/bin:$PATH"
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - cask install

script:
  - cask build
  - cask package

after_success:
  - echo "Success!"
